### ISSUE TITLE
Icons and caption not working

### ISSUE THREAD

**Issue by EggJacktly** [shafayetShafee/collapse-social-embeds#2]
There is an issue with Icons and Captions of all the social embeds.
The video file is working properly, ```collapse=true```, ```icon=false``` and colors of callouts are working as intended.

Quarto Version: 1.3.450

I'm using the following code block in document yml :
```
---
title: "Title"
format: html
filters:
  - collapse-social-embeds
execute:
  echo: false
jupyter: python3
---
```
And the following code in markdown qmd:
```
::: {.youtube video_id=hTqw_CGCmNs caption="Youtube Video" }
:::

::: {.mastodon url="https://fosstodon.org/@pandoc/109712438144865859" }
:::

::: {.gist user=tarleb gist_id=852f6ae98764bea56aeeac979f3c17be icon=true collapse=true icon=false caption="A Caption" }
:::
```
This results in the following:

<img width="584" alt="extension_bug" src="https://github.com/shafayetShafee/collapse-social-embeds/assets/28916652/2df35494-44f8-4d6a-acae-a704b8bde6e9">

**Comment by shafayetShafee** [comment]
This problem happened because [`caption` is renamed to `title` in the callout constructor](https://github.com/quarto-dev/quarto-cli/pull/4449). However, this issue has been resolved now. So install the filter again and use `title` instead of `caption`. Everything should work as intended now.
